### PR TITLE
fix "syanpse" and "configruation" misspellings

### PR DESCRIPTION
**Pull request by swedneck**
Signed-off-by: Tim Stahel <swedneck@swedneck.xyz>

### CODE REVIEW

**Comment by Half-Shot** [comment]
Good eye! Sign off as per the CONTRIBUTING.md file please :)

**Comment by swedneck** [comment]
@Half-Shot done

**Comment by Half-Shot** [comment]
Also this should be against `develop`

**Comment by swedneck** [comment]
@Half-Shot also fixed

**Pull request merged**
