### PR TITLE
Update PgDatastore.ts

### PR DESCRIPTION
**Pull request by vitaly-t**
Having fun with your queries :smile: (pg-promise author)

### CODE REVIEW

**Comment by Half-Shot** [comment]
Heya, thanks for contributing :). Just so you're aware:
- changes are based off the `develop` branch
- each change needs a newsfile: create a file called `changelog.d/297.misc` with a small note about your changes, and credit yourself.

**Comment by vitaly-t** [comment]
Sorry, my desire for frivolous coding lasted as long as the did the beer. I'm fresh out. Use the suggested changes or not, up to you :smile:

**Comment by turt2live** [comment]
@vitaly-t is it possible to at least get sign off so we are in a position to use this? Just need a comment along the lines of:

```
Signed-off-by: Your Name <email@example.org>
```

**Comment by Half-Shot** [comment]
We won't be able to make use of these changes because we legally cannot do so without a sign off. I'm going to close this for now as the changes do not make a substantial difference to the behavior.

**Pull request closed without merging**
