### PR TITLE
Allow syncing Bot messages from Slack to Matrix

### LINKED ISSUE #42: Messages from other apps in Slack (that use attachments) are silently ignored
Hey,
just noticed that messages from apps like the RSS integration are silently ignored. This might be related to #37 as both are not ordinary messages.
This can cause confusing conversations when other team members refer to something that was posted by another app ;)

### PR DESCRIPTION
**Pull request by MTRNord**
This is untested! (I have no HS access to test but it is according to the slack Spec https://api.slack.com/events/message/bot_message )

This should fix #42 but as said I am not able to test it myself

### CODE REVIEW

**Comment by erdnaxeli** [comment]
I try this this week-end.

**Comment by erdnaxeli** [comment]
Okay, it's more complex than that, see #29. We need to move from outgoing-webhook to a real bot user.

**Comment by MTRNord** [comment]
@erdnaxeli hm ok :/ the doc/spec meant it should work also with webhooks :( but ok I will close this to not cause confusion

**Comment by MTRNord** [comment]
grafik

(Event API should be Webhooks)

**Comment by MTRNord** [comment]
nvm apperantly Webhooks ARE NOT Events Api :/

**Comment by erdnaxeli** [comment]
This is not the problem. The event is correctly received, but the code ignore it (https://github.com/matrix-org/matrix-appservice-slack/blob/master/lib/SlackHookHandler.js#L182).

**Comment by MTRNord** [comment]
Oh Hm well ok i will Take a look at making that check better.

**Comment by MTRNord** [comment]
Looking at the Code we already can get our bot ID when registering the webhook/getting the OAuth2 access_token. This is documented in: https://api.slack.com/bot-users Under the "Retrieving your bot user token" Section. In there is a "bot_user_id" field which should contain the ID of our bot and should be useable. I will see if I can implement all the stuff needed to "fix"/change the if you refered too.

**Pull request closed without merging**
