### PR TITLE
tiny typos

### PR DESCRIPTION
**Pull request by andreasnuesslein**

### CODE REVIEW

**Comment by Half-Shot** [comment]
Hey @andreasnuesslein, thanks for the contribution. Can you add a sign off and a newsfile as per [this doc](https://github.com/matrix-org/matrix-appservice-slack/blob/ea75b3d610822406500f9935f2acdc488aa6a53b/CONTRIBUTING.md#making-pull-requests)

**Comment by andreasnuesslein** [comment]
Like so? Or do I need to sign of the first commit as well?

**Comment by Half-Shot** [comment]
Either is fine :)

**Comment by Half-Shot** [comment]
Err, this should have been against `develop`

**Pull request merged**
