### PR TITLE
Update PgDatastore.ts

### PR DESCRIPTION
**Pull request by vitaly-t**
Just some examples of better use of `pg-promise`, from the author :wink:

Signed-off-by: Vitaly Tomilov <vitaly.tomilov@gmail.com>

### CODE REVIEW

**Comment by Half-Shot** [comment]
Heya, thanks for contributing :smile:. Would you mind signing off your PR as per [CONTRIBUTING.md](https://github.com/matrix-org/matrix-appservice-slack/blob/develop/CONTRIBUTING.md#making-pull-requests):

It basically boils down to adding
```
Signed-off-by: Your Name <your@email.example.org>
```

to your PR description.

**Comment by vitaly-t** [comment]
Added ;)

**Comment by Half-Shot** [comment]
Linter still seems unhappy :(

**Comment by jaller94** [comment]
The linter's issues:
Screenshot_2020-07-21_19-56-03

**Comment by jaller94** [comment]
https://github.com/matrix-org/matrix-appservice-slack/commit/0fca58486e7ce474937766678f3ae92c11488a93 fixes these issues.
I wasn't able to push to this (probably just not knowing Git and GitHub's PR system well enough), so I opened #439.

**Pull request merged**
